name:Pasos en flujo de trabajo
on:
  push:
    branches:["master"]
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - name:Clonar
  uses:actions/checkout@v2
  - name:Compilar
  run: npm install && npm run build
  - name: Desplegar
  uses:action-deploy@v1
  with:
  server:production
